name: С++ CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.28.0

    - name: Check CMake version
      run: cmake --version
      
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
